version: "3.9"
services:
  db:
    image: postgres:14
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  subscription-service:
    build: ./subscription_service
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

  notification-service:
    build: ./notification_service
    depends_on:
      - rabbitmq
